apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- prometheus-config.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- node-exporter-daemonset.yaml
- node-exporter-service.yaml 