apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoramento-config
  namespace: autocura-cognitiva
data:
  config.yaml: |
    collection_interval: 15
    retention_period_days: 7
    anomaly_detection_sensitivity: 0.8
    collectors:
      - name: throughput
        enabled: true
        interval: 10
      - name: errors
        enabled: true
        interval: 5
      - name: latency
        enabled: true
        interval: 10
      - name: resources
        enabled: true
        interval: 30
    aggregation:
      window_size: 60
      overlap: 15
      methods:
        - mean
        - median
        - percentile_95
    alerts:
      threshold_critical: 0.9
      threshold_warning: 0.7
      channels:
        - slack
        - email
