apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoramento
  namespace: autocura-cognitiva
  labels:
    app: monitoramento
    component: autocura-cognitiva
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoramento
  template:
    metadata:
      labels:
        app: monitoramento
    spec:
      serviceAccountName: autocura-cognitiva-sa
      containers:
      - name: monitoramento
        image: autocura-cognitiva/monitoramento:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CONFIG_MAP
          value: monitoramento-config
        - name: LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: monitoramento-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: autocura-cognitiva-data
