apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoramento-rolebinding
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: monitoramento
    app.kubernetes.io/part-of: components
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoramento-role
subjects:
- kind: ServiceAccount
  name: monitoramento
  namespace: autocura-cognitiva 