kind: Cluster 
apiVersion: kind.x-k8s.io/v1alpha4 
name: autocura-cognitiva 
nodes: 
- role: control-plane 
  extraPortMappings: 
  - containerPort: 30000 
    hostPort: 30000 
    protocol: TCP 
  - containerPort: 30001 
    hostPort: 30001 
    protocol: TCP 
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://registry:5000"]
