apiVersion: v1
kind: Namespace
metadata:
  name: healing-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healing-operator-controller-manager
  namespace: healing-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: healing-operator-controller-manager
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: localhost:5000/autocura-cognitiva/healing-operator:dev
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10 