apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoramento
spec:
  replicas: 1
  configSecret: alertmanager-config
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi 