apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoramento
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'default'

    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://observabilidade:8002/alerts'
        send_resolved: true 