apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura-cognitiva

resources:
- alertmanager.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: alertmanager
  app.kubernetes.io/part-of: monitoramento 