// +build !ignore_autogenerated

// Código gerado pelo controller-gen. NÃO EDITAR.

package v1

import (
    "k8s.io/apimachinery/pkg/runtime"
)

// ... (métodos DeepCopy gerados automaticamente, compatíveis com runtime.Object)