apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-operator
  namespace: autocura-cognitiva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollback-operator
  template:
    metadata:
      labels:
        app: rollback-operator
    spec:
      serviceAccountName: autocura-cognitiva-sa
      containers:
      - name: rollback-operator
        image: autocura-cognitiva/rollback-operator:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "rollback-operator"
