apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollback-operator-rolebinding
  namespace: autocura-cognitiva
subjects:
- kind: ServiceAccount
  name: rollback-operator
  namespace: autocura-cognitiva
roleRef:
  kind: Role
  name: rollback-operator-role
  apiGroup: rbac.authorization.k8s.io 