apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollbackpolicies.rollback.autocura-cognitiva.io
spec:
  group: rollback.autocura-cognitiva.io
  names:
    kind: RollbackPolicy
    listKind: RollbackPolicyList
    plural: rollbackpolicies
    shortNames:
    - rp
    singular: rollbackpolicy
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.lastAppliedStatus
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: RollbackPolicy define uma política de rollback para recursos Kubernetes
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RollbackPolicySpec define a especificação desejada para uma
              RollbackPolicy
            properties:
              checkInterval:
                description: Intervalo de verificação em segundos
                format: int32
                type: integer
              conditions:
                description: Condições que acionam o rollback
                items:
                  description: RollbackCondition define uma condição que aciona o rollback
                  properties:
                    maxContainerRestarts:
                      description: Número máximo de reinícios de contêiner antes de
                        acionar rollback
                      format: int32
                      type: integer
                    minDuration:
                      description: Duração mínima da condição antes de acionar o rollback
                        (em segundos)
                      format: int32
                      type: integer
                    minUnavailablePercent:
                      description: Porcentagem mínima de pods não disponíveis para acionar
                        rollback
                      format: int32
                      type: integer
                    status:
                      description: Status esperado (True, False, Unknown)
                      type: string
                    type:
                      description: Tipo de condição (Progressing, Available, etc.)
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              cooldownPeriod:
                description: Tempo de espera após rollback antes de permitir nova verificação
                  (em segundos)
                format: int32
                type: integer
              maxAttempts:
                description: Número máximo de tentativas de rollback
                format: int32
                type: integer
              selector:
                description: Seletor para os recursos alvo desta política
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that contains
                        values, a key, and an operator that relates the key and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to a
                            set of values. Valid operators are In, NotIn, Exists and
                            DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the operator
                            is In or NotIn, the values array must be non-empty. If the
                            operator is Exists or DoesNotExist, the values array must
                            be empty. This array is replaced during a strategic merge
                            patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator is
                      "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
              targetNamespace:
                description: Namespace alvo (vazio para todos os namespaces)
                type: string
              targetRevision:
                description: Revisão para a qual fazer rollback (0 para a revisão anterior)
                format: int32
                type: integer
            required:
            - conditions
            - selector
            type: object
          status:
            description: RollbackPolicyStatus define o status observado de uma RollbackPolicy
            properties:
              appliedCount:
                description: Número de vezes que esta política foi aplicada
                format: int32
                type: integer
              currentRevisions:
                additionalProperties:
                  format: int32
                  type: integer
                description: Revisão atual dos recursos monitorados
                type: object
              lastAppliedMessage:
                description: Mensagem da última aplicação
                type: string
              lastAppliedStatus:
                description: Status da última aplicação (Succeeded, Failed)
                type: string
              lastAppliedTime:
                description: Última vez que esta política foi aplicada
                format: date-time
                type: string
              monitoredResources:
                description: Recursos atualmente monitorados por esta política
                items:
                  type: string
                type: array
              rollbackRevisions:
                additionalProperties:
                  format: int32
                  type: integer
                description: Revisões para as quais foi feito rollback
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: RollbackPolicy
    listKind: RollbackPolicyList
    plural: rollbackpolicies
    shortNames:
    - rp
    singular: rollbackpolicy
  conditions:
  - lastTransitionTime: "2023-04-26T01:00:00Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-04-26T01:00:00Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
