apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollbacks.rollback.autocura-cognitiva.io
spec:
  group: rollback.autocura-cognitiva.io
  names:
    kind: Rollback
    listKind: RollbackList
    plural: rollbacks
    singular: rollback
    shortNames:
    - rb
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              target:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
              backup:
                type: object
                properties:
                  name:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  format:
                    type: string
              status:
                type: string
                enum:
                - Pending
                - InProgress
                - Completed
                - Failed
              error:
                type: string
              lastUpdated:
                type: string
                format: date-time 