apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostico
  namespace: autocura-cognitiva
  labels:
    app: diagnostico
    component: autocura-cognitiva
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diagnostico
  template:
    metadata:
      labels:
        app: diagnostico
    spec:
      serviceAccountName: autocura-cognitiva-sa
      containers:
      - name: diagnostico
        image: autocura-cognitiva/diagnostico:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: MONITORAMENTO_URL
          value: "http://monitoramento:8080"
        - name: CONFIG_MAP
          value: diagnostico-config
        - name: LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: models-volume
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: diagnostico-config
      - name: models-volume
        persistentVolumeClaim:
          claimName: autocura-cognitiva-models
