apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: diagnostico-role
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: diagnostico
    app.kubernetes.io/part-of: components
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "podmonitors"]
  verbs: ["get", "list", "watch"] 