apiVersion: v1
kind: Service
metadata:
  name: diagnostico
  namespace: autocura-cognitiva
  labels:
    app: diagnostico
    component: autocura-cognitiva
spec:
  selector:
    app: diagnostico
  ports:
  - port: 8081
    targetPort: http
    name: http
  type: ClusterIP
