apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollbackpolicies.autocura.cognitiva.io
spec:
  group: autocura.cognitiva.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                metrics:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      weight:
                        type: number
                      threshold:
                        type: number
                      comparisonOperator:
                        type: string
                        enum: [GreaterThan, LessThan, Equal]
                probabilityThreshold:
                  type: number
                  minimum: 0
                  maximum: 1
                observationWindowSeconds:
                  type: integer
                rollbackToRevision:
                  type: string
                successCriteria:
                  type: object
                  properties:
                    metricName:
                      type: string
                    threshold:
                      type: number
                    comparisonOperator:
                      type: string
                      enum: [GreaterThan, LessThan, Equal]
                    durationSeconds:
                      type: integer
            status:
              type: object
              properties:
                currentProbability:
                  type: number
                lastEvaluation:
                  type: string
                  format: date-time
                lastRollback:
                  type: string
                  format: date-time
                observations:
                  type: array
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      metrics:
                        type: object
                        additionalProperties:
                          type: number
                      probability:
                        type: number
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
  scope: Namespaced
  names:
    plural: rollbackpolicies
    singular: rollbackpolicy
    kind: RollbackPolicy
    shortNames:
    - rbp
