apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura-cognitiva

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml
- secrets.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoramento 