apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoramento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 