apiVersion: apps/v1
kind: Deployment
metadata:
  name: all
spec:
  template:
    spec:
      containers:
      - name: monitoramento
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      - name: diagnostico
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
      - name: gerador-acoes
        resources:
          limits:
            cpu: 3000m
            memory: 3Gi
          requests:
            cpu: 750m
            memory: 1.5Gi
      - name: observabilidade
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
