apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura-cognitiva

resources:
- namespace.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- configmap.yaml
- secrets.yaml

labels:
- pairs:
    app.kubernetes.io/name: autocura-cognitiva
    app.kubernetes.io/part-of: autocura-cognitiva

commonAnnotations:
  description: "Configurações base do Sistema de Autocura Cognitiva"
