apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- rbac/role.yaml
- rbac/rolebinding.yaml
- configmap.yaml

labels:
  app.kubernetes.io/part-of: autocura-cognitiva
  app.kubernetes.io/managed-by: kustomize
