apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healings.healing.autocura-cognitiva.io
spec:
  group: healing.autocura-cognitiva.io
  names:
    kind: Healing
    listKind: HealingList
    plural: healings
    singular: healing
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              checkInterval:
                type: integer
                description: Intervalo de verificação em segundos
          status:
            type: object
            properties:
              lastAppliedTime:
                type: string
                format: date-time
              lastAppliedStatus:
                type: string
              lastAppliedMessage:
                type: string
              appliedCount:
                type: integer 