apiVersion: monitoring.coreos.com/v1
kind: Grafana
metadata:
  name: observabilidade-grafana
  namespace: autocura-cognitiva
spec:
  serviceAccountName: grafana
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  config:
    security:
      admin_user: admin
      admin_password: admin
    auth:
      disable_login_form: false
      disable_signout_menu: false
    log:
      mode: console
      level: info
    server:
      http_port: 3000
      root_url: https://grafana.example.com
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_role: Editor 