apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoramento
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-role
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: autocura-cognitiva 