apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: autocura-cognitiva
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoramento
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus 