apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base
- components/monitoramento
- components/diagnostico
- components/gerador-acoes
- components/observabilidade
- operators/healing-operator
- operators/rollback-operator
- storage

commonLabels:
  app.kubernetes.io/part-of: autocura-cognitiva
  app.kubernetes.io/managed-by: kustomize

namespace: autocura-cognitiva

# Configuração para seleção de ambiente
# Descomente apenas um dos overlays abaixo para selecionar o ambiente desejado

# Para ambiente de desenvolvimento:
# patchesStrategicMerge:
# - environments/development/kustomization.yaml

# Para ambiente de staging:
# patchesStrategicMerge:
# - environments/staging/kustomization.yaml

# Para ambiente de produção:
# patchesStrategicMerge:
# - environments/production/kustomization.yaml
