apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura-cognitiva

resources:
- persistentvolume.yaml
- persistentvolumeclaim-data.yaml
- persistentvolumeclaim-models.yaml
- persistentvolumeclaim-templates.yaml
- persistentvolumeclaim-visualizacoes.yaml

labels:
- pairs:
    app.kubernetes.io/name: storage
    app.kubernetes.io/part-of: autocura-cognitiva

commonAnnotations:
  description: "Configurações de armazenamento para o Sistema de Autocura Cognitiva"
