apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: autocura-cognitiva
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi 