apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-cognitiva-data
  namespace: autocura-cognitiva
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-cognitiva-models
  namespace: autocura-cognitiva
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-cognitiva-templates
  namespace: autocura-cognitiva
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-cognitiva-visualizacoes
  namespace: autocura-cognitiva
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
