apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healing-operator-role
rules:
- apiGroups:
  - healing.autocura-cognitiva.io
  resources:
  - healings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healing.autocura-cognitiva.io
  resources:
  - healings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch 