apiVersion: v1
kind: ConfigMap
metadata:
  name: gerador-acoes-config
  namespace: autocura-cognitiva
data:
  config.yaml: |
    action_validation_enabled: true
    simulation_iterations: 100
    risk_threshold: 0.3
    action_strategies:
      hotfix:
        enabled: true
        priority: high
        max_concurrent: 3
        validation_required: false
      refatoracao:
        enabled: true
        priority: medium
        max_concurrent: 2
        validation_required: true
      redesign:
        enabled: true
        priority: low
        max_concurrent: 1
        validation_required: true
    genetic_algorithm:
      population_size: 50
      generations: 20
      mutation_rate: 0.1
      crossover_rate: 0.7
      selection_method: tournament
      fitness_weights:
        efficacy: 0.5
        risk: 0.3
        resource_usage: 0.1
        implementation_time: 0.1
    simulation:
      enabled: true
      parallel_simulations: 8
      max_simulation_time: 300
      confidence_threshold: 0.85
