apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerador-acoes
  namespace: autocura-cognitiva
  labels:
    app: gerador-acoes
    component: autocura-cognitiva
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gerador-acoes
  template:
    metadata:
      labels:
        app: gerador-acoes
    spec:
      serviceAccountName: autocura-cognitiva-sa
      containers:
      - name: gerador-acoes
        image: gerador-acoes:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
          name: http
        resources:
          limits:
            cpu: 1500m
            memory: 1.5Gi
          requests:
            cpu: 750m
            memory: 768Mi
        env:
        - name: DIAGNOSTICO_URL
          value: "http://diagnostico:8081"
        - name: CONFIG_MAP
          value: gerador-acoes-config
        - name: LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: templates-volume
          mountPath: /app/templates
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: gerador-acoes-config
      - name: templates-volume
        persistentVolumeClaim:
          claimName: autocura-cognitiva-templates
