apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/component: gerador-acoes
  app.kubernetes.io/part-of: autocura-cognitiva
  app.kubernetes.io/managed-by: kustomize

namePrefix: gerador-acoes-
