apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- crds/healingpolicy.yaml

commonLabels:
  app.kubernetes.io/component: healing-operator
  app.kubernetes.io/part-of: autocura-cognitiva
  app.kubernetes.io/managed-by: kustomize

namePrefix: healing-
