apiVersion: autocura.cognitiva.io/v1
kind: HealingPolicy
metadata:
  name: monitoramento-healing-policy
  namespace: autocura-cognitiva
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoramento
    namespace: autocura-cognitiva
  metrics:
    - name: cpu-utilization
      type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - name: memory-utilization
      type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - name: latency
      type: Custom
      custom:
        metricName: api_latencia_media
        threshold: 100
  actions:
    - type: Scale
      scale:
        minReplicas: 2
        maxReplicas: 5
    - type: Restart
      restart:
        gracePeriodSeconds: 30
    - type: Reconfigure
      reconfigure:
        configMap: monitoramento-config
        key: collection_interval
        value: "30"
  cooldownSeconds: 300
  maxAttempts: 3
