apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healingpolicies.autocura.cognitiva.io
spec:
  group: autocura.cognitiva.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                metrics:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                        enum: [Resource, Custom]
                      resource:
                        type: object
                        properties:
                          name:
                            type: string
                          target:
                            type: object
                            properties:
                              type:
                                type: string
                                enum: [Utilization, Value]
                              averageUtilization:
                                type: integer
                              averageValue:
                                type: string
                      custom:
                        type: object
                        properties:
                          metricName:
                            type: string
                          threshold:
                            type: number
                actions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [Scale, Restart, Reconfigure, Custom]
                      scale:
                        type: object
                        properties:
                          replicas:
                            type: integer
                          minReplicas:
                            type: integer
                          maxReplicas:
                            type: integer
                      restart:
                        type: object
                        properties:
                          gracePeriodSeconds:
                            type: integer
                      reconfigure:
                        type: object
                        properties:
                          configMap:
                            type: string
                          key:
                            type: string
                          value:
                            type: string
                      custom:
                        type: object
                        properties:
                          command:
                            type: string
                          args:
                            type: array
                            items:
                              type: string
                cooldownSeconds:
                  type: integer
                maxAttempts:
                  type: integer
            status:
              type: object
              properties:
                lastHealing:
                  type: string
                  format: date-time
                attempts:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
  scope: Namespaced
  names:
    plural: healingpolicies
    singular: healingpolicy
    kind: HealingPolicy
    shortNames:
    - hp
